### ISSUE TITLE
e2e: allocation tests fail on L2

### ISSUE THREAD

**Issue by tmigone** [graphprotocol/contracts#900]
This happens _randomly_ when the full e2e tests run on GitHub actions:

```
== Open allocations

Allocating 25000000000000000000000 tokens on 0x85045f3A354F59017d83fD5fD23772fCa1240981...

Allocating 50000000000000000000000 tokens on 0xaEBd5f939B2783Ed57a568EeB2ac8C3Bc7b81CEc...

Allocating 10000000000000000000000 tokens on 0x46FC48997f35a95353B0a7C76f8c766714dE8961...

Allocating 25000000000000000000000 tokens on 0xdb90333a6f86645541dF5Db0B26bCd4BcC366DDC...

Allocating 10000000000000000000000 tokens on 0xc4966F99b46E8c611897bBF9242feB9d4D673d13...

Allocating 10000000000000000000000 tokens on 0xB6C6A863aBa8a98955C16fD2eC9e952fab0cF0Df...
Error: transaction failed [ See: https://links.ethers.org/v5-errors-CALL_EXCEPTION ] (transactionHash="0xbf0719dfff16e304f860e1a5f61e675dae167e4ecf66405a93dafee4550cd367", transaction={"hash":"0xbf0719dfff16e304f860e1a5f61e675dae167e4ecf66405a93dafee4550cd367","type":2,"accessList":[],"blockHash":"0x4febea011e4dbeb8eee48873a065f0eb3051034a3169f24e57c1e1925a3195c2","blockNumber":164,"transactionIndex":1,"confirmations":1,"from":"0x2f97a7Df3d2Ada745B951697939eE28814798467","gasPrice":{"type":"BigNumber","hex":"0x05f5e100"},"maxPriorityFeePerGas":{"type":"BigNumber","hex":"0x00"},"maxFeePerGas":{"type":"BigNumber","hex":"0x078b30c4"},"gasLimit":{"type":"BigNumber","hex":"0x03fe3f"},"to":"0xD2e2C99Bf402EeE368Ca1CB105561b0919a7D0DC","value":{"type":"BigNumber","hex":"0x00"},"nonce":4,"data":"0x23477e480000000000000000000000002f97a7df3d2ada745b951697939ee288147984673093dadafd593b5c2d10c16bf830e96fc41ea7b91d7dabd032b44331fb2a7e5100000000000000000000000000000000000000000000021e19e0c9bab2400000000000000000000000000000b6c6a863aba8a98955c16fd2ec9e952fab0cf0df000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000c0000000000000000000000000000000000000000000000000000000000000004139c7e857af8562381b380e04b047606745e018c2f134d425ded0467558a617de5a433d0eaa8af44cee06c996b2e073325252bd09b28bbe76849b20601243bc3c1c00000000000000000000000000000000000000000000000000000000000000","r":"0xa99227168af037cabf95b78291f7740e843dd648b3e8c1b22ee591fa8fec29c8","s":"0x0a10a0d004a19ed1f0463861f80ffd8a7a910d76bb404cd2093b147d423fb009","v":1,"creates":null,"chainId":412346}, receipt={"to":"0xD2e2C99Bf402EeE368Ca1CB105561b0919a7D0DC","from":"0x2f97a7Df3d2Ada745B951697939eE28814798467","contractAddress":null,"transactionIndex":1,"gasUsed":{"type":"BigNumber","hex":"0x03f061"},"logsBloom":"0x00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000","blockHash":"0x4febea011e4dbeb8eee48873a065f0eb3051034a3169f24e57c1e1925a3195c2","transactionHash":"0xbf0719dfff16e304f860e1a5f61e675dae167e4ecf66405a93dafee4550cd367","logs":[],"blockNumber":164,"confirmations":1,"cumulativeGasUsed":{"type":"BigNumber","hex":"0x03f061"},"effectiveGasPrice":{"type":"BigNumber","hex":"0x05f5e100"},"status":0,"type":2,"byzantium":true}, code=CALL_EXCEPTION, version=providers/5.7.2)
    at Logger.makeError (/home/runner/work/contracts/contracts/node_modules/@ethersproject/logger/src.ts/index.ts:269:28)
    at Logger.throwError (/home/runner/work/contracts/contracts/node_modules/@ethersproject/logger/src.ts/index.ts:281:20)
    at EthersProviderWrapper.<anonymous> (/home/runner/work/contracts/contracts/node_modules/@ethersproject/providers/src.ts/base-provider.ts:1549:24)
No need to generate any newer typings.


  Open allocations
    GRT balances
      ✔ indexer balances should match airdropped amount minus staked
    Staking
      ✔ indexers should have staked tokens
    Allocations
      1) allocatons should be open


  2 passing (113ms)
  1 failing

  1) Open allocations
       Allocations
         allocatons should be open:

      AssertionError: expected +0 to equal 1
      + expected - actual

      -0
      +1
      
      at Context.<anonymous> (e2e/scenarios/open-allocations.test.ts:42:23)
      at processTicksAndRejections (node:internal/process/task_queues:95:5)



Error: Process completed with exit code 1.
```

**Comment by tmigone** [comment]
Example: https://github.com/graphprotocol/contracts/actions/runs/7303228191/job/19903323661
